name = "edenpack"
author = "cwage"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fdf255f0c925e346689235dab541df688b92083a0711a25610dbd092aebf6a2c"

[versions]
fabric = "0.19.2"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21", "1.21.11"]
