name = "edenpack"
author = "cwage"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "569c6bc3fe8de3a0261e44883bc154d00434c56f9f24251c61b71d51d9d45207"

[versions]
fabric = "0.19.2"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21", "1.21.11"]
